#!/bin/sh -e
#    man - download and read manpages from the web, rather than your local system
#
# Copyright 2024 Chainguard, Inc.
# Author: Dustin Kirkland <kirkland@chainguard.dev>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e

# Allow for REPO override in an environment variable (for testing)
[ -z "$REPO" ] && REPO="https://web-v1-enfmknn37q-uc.a.run.app"

# Try to use a system wide cache, but also support user local
CACHE="/var/cache/man/"
INDEX="$INDEX/manpages.index.gz"
if [ ! -w "$CACHE" ] || [ ! -w "$INDEX" ]; then
	CACHE="$HOME/.man"
	mkdir -p "$CACHE"
	INDEX="$CACHE/manpages.index.gz"
fi

PAGE=$(echo "$@" | awk '{print $NF}')
MAN_ARGS=$(echo "$@" | sed "s/\$PAGE$//")
[ ! -z "$LANG" -a -z "$LOCALE" ] && LOCALE="$LANG" || true
[ ! -z "$LC_MESSAGES" -a -z "$LOCALE" ] && LOCALE="$LC_MESSAGES" || true
[ "$LOCALE" = "C" -o "$LOCALE" = "C.UTF-8" ] && LOCALE="" || true
[ ! -z "$LOCALE" ] && LOCALE="${LOCALE%%_*}" || true
if [ ! -z "$LOCALE" -a "$LOCALE" != "en" -a "$LOCALE" != "C.UTF-8" ]; then
	GREP="^manpages/man\/$LOCALE.*\/$PAGE\..*gz"
else
	GREP="^manpages/man\/man.\/$PAGE\..*gz"
fi

update_cache() {
	# If we have no index, or the index is more than a day old, update cache
	if [ ! -s "$INDEX" ] || [ $(find "$INDEX" -mmin +1440) ]; then
		rm -f "$INDEX"
		wget -q -O"$INDEX" "$REPO/manpages.index.gz"
	fi
}

search_index() {
	local regex="$1"
	local matches=$(zcat "$INDEX" | grep -c "$regex")
	case "$matches" in
		0)
			if $(zcat $INDEX | grep -q "$PAGE"); then
				echo "ERROR: No exact matches; did you mean one of:"
				zcat "$INDEX" | sed -e "s/.*\///" | grep "$PAGE" | sed -e "s/^/  - /" -e "s/\.gz$//" -e "s/\.[0-9]//" | sort -u
				exit 1
			else
				echo "ERROR: No manpage matches for '$PAGE'" 1>&2
			fi
		;;
		1)
			# Bingo.  Exactly one match.  Fetch and render.
			fetch_and_render "$regex"
		;;
		*)
			echo "ERROR: Multiple matches for '$PAGE'" 1>&2
			zcat "$INDEX" | grep "$regex" | sed -e "s/.*\///" | sed -e "s/^/  - /" -e "s/\.gz$//"
			exit 1
		;;
	esac
}

fetch_and_render() {
	local regex="$1"
	local i=$(zcat "$INDEX" | grep -m1 "$regex" | sed -e "s:^manpages/::")
	local man="$CACHE/$i"
	mkdir -p $(dirname "$man")
	if wget -O "$man" "$REPO/$i"; then
#		if echo "$man" | egrep -q "\.htm.gz|\.html.gz|\.xml.gz"; then
#			w3m "$man"
		if echo "$man" | grep -q "man/cat"; then
			# Handle weird, pre-formatted catman pages
			zcat "$man" | less -f -R -
		else
			zcat "$man" | man $MAN_ARGS -l -
		fi
	fi
}

update_cache
search_index "$GREP"
